version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["node", "dist/apps/api-gateway/main.js"]

  orders:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    command: ["node", "dist/apps/orders/main.js"]

  users:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    command: ["node", "dist/app/users/main.js"]
